### ISSUE TITLE
looking to convert my dom based action rpg to this

### ISSUE THREAD

**Issue by McFarts** [RoganMurley/hitagi.js#8]
For example:

![](https://i.gyazo.com/857c840b1911faba53570b8974167b84.gif)

All Dom based, no canvas.

Need to use canvas because I'm at the point where.. mob movement, css3 transitions and everything are making the screen lag.

Possible with this engine? :) Ty

**Comment by RoganMurley** [comment]
Definitely possible!

If you've already got a game built and just need to change how you render, you might be better off using something like [pixi](https://github.com/pixijs/pixi.js) that's dedicated just to rendering. Otherwise you'll need to change to the 'Hitagi way' of doing things (Entity Component System e.t.c.).

**Comment by McFarts** [comment]
Alrighty, thanks.

I really love the ECS system, I love javascript notation and so used to it.

**Comment by RoganMurley** [comment]
Let me know if you do end up using it! :)
